"""Recreating migrations

Revision ID: f45b3e235fbc
Revises: 
Create Date: 2025-02-06 10:57:36.052980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f45b3e235fbc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('receiver_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['receiver_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['member.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_chat_message')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_chat_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('sender_id', sa.INTEGER(), nullable=False),
    sa.Column('receiver_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['receiver_id'], ['member.id'], name='fk_chat_message_receiver'),
    sa.ForeignKeyConstraint(['sender_id'], ['member.id'], name='fk_chat_message_sender'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('chat_message')
    # ### end Alembic commands ###
